=== 12antonio/trabajoXML/validador.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="libreria" type="LibrosFic" />

  <xsd:complexType name="LibrosFic">
    <xsd:sequence>
      <xsd:element name="lista_libros" type="LibroFic" />
      <xsd:element name="proveedor" type="proveedores"/>
    </xsd:sequence>

  
  </xsd:complexType>

  <xsd:complexType name="LibroFic">
    <xsd:sequence>
      <xsd:element name="libros" type="libros" maxOccurs="unbounded" />
    </xsd:sequence>
  
  </xsd:complexType>
  <xsd:complexType name="libros">
    <xsd:sequence>
      <xsd:element name="titulo" type="xsd:string" />
      <xsd:element name="autor" type="xsd:string" minOccurs="0" />
      <xsd:element name="aÃ±o" type="tipoFecha" />
      <xsd:element name="precio" type="xsd:float" />
      <xsd:element name="disponible" type="xsd:boolean" />
  </xsd:sequence>
  <xsd:attribute name="idlibro" type="xsd:string" />
  </xsd:complexType>

  <xsd:simpleType name="tipoFecha">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-3]?[0-9]/[0-1]?[0-9]/[0-9]{4}"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="proveedores">
    <xsd:sequence>
    <xsd:element name="nombre" type="xsd:string"/>
    <xsd:element name="apellido" type="xsd:string" />
    <xsd:element name="cif" type="tipoCif" />
    <xsd:element name="direccion" type="xsd:string" />
    <xsd:element name="telefono" type="tipoTelefono" />
    <xsd:element name="reparto" type="tipoReparto" />
    <xsd:element name="horario" type="tipoHora"/>
  </xsd:sequence>
  </xsd:complexType>
<xsd:simpleType name="tipoCif">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z]?\d{8}[A-Z]"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="tipoTelefono">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[+]{1}[3/4]{2} [0-9]{9}"/>
    </xsd:restriction>
</xsd:simpleType>
  <xsd:simpleType name="tipoReparto">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="lunes|martes|miercoles|jueves|viernes"/>
    </xsd:restriction>
  </xsd:simpleType>
<xsd:simpleType name="tipoHora">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-2][0-9]:[0-5][0-9]"/>
    </xsd:restriction>
</xsd:simpleType>
  
</xsd:schema>

=== 12antonio/trabajoXML/libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xslt"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="validador.xsd">


<lista_libros>

    <libros idlibro="libro1()"> <!--Código de libro-->
        <titulo>Lazarillo</titulo>
        
        <año>3/12/1536</año>
        <precio>50</precio>
        <disponible>true</disponible>
    </libros>

    <libros idlibro="libro2()"> <!--Código de libro-->
        <titulo>El Quijote</titulo>
        <autor>Cervantes</autor>
        <año>20/5/1548</año>
        <precio>2000</precio>
        <disponible>false</disponible>

    </libros>

    <libros idlibro="libro3()"> <!--Código de libro-->
        <titulo>Harry Potter</titulo>
        <autor>JK.Rowlling</autor>
        <año>22/6/2008</año>
        <precio>20</precio>
        <disponible>true</disponible>

    </libros>
</lista_libros>

<proveedor>

    <nombre>antonio</nombre>
    <apellido>Buendia</apellido>
    <cif>B25895489V</cif>
    <direccion>calle Tajo 9</direccion>
    <telefono>+34 632598478</telefono>
    <reparto>lunes</reparto>
    <horario>12:00</horario>


</proveedor>

</libreria>
